apiVersion: v1
kind: Namespace
metadata:
  name: shopping

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributedcache
  namespace: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributedcache
  template:
    metadata:
      labels:
        app: distributedcache
    spec:
      containers:
      - name: distributedcache
        image: redis
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: distributedcache
  namespace: shopping
spec:
  type: ClusterIP
  selector:
    app: distributedcache
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-grpc
  namespace: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount-grpc
  template:
    metadata:
      labels:
        app: discount-grpc
    spec:
      containers:
      - name: discount-grpc
        image: discountgrpc:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        - name: ConnectionStrings__Database
          value: "Data Source=discountdb"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /home/app/.microsoft/usersecrets
          name: user-secrets
        - mountPath: /home/app/.aspnet/https
          name: aspnet-https
      volumes:
      - name: user-secrets
        emptyDir: {}
      - name: aspnet-https
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: discount-grpc
  namespace: shopping
spec:
  type: LoadBalancer
  selector:
    app: discount-grpc
  ports:
    - name: http
      protocol: TCP
      port: 6002
      targetPort: 8080